import PageLayout from "@/app/components/PageLayout";
import PageBackground3D from "@/app/components/PageBackground3D";

export default function TermsPage() {
  return (
    <PageLayout>
      <section className="relative overflow-hidden pt-20 pb-32">
        <div className="absolute inset-0 pointer-events-none">
<div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-brand/10 rounded-full blur-[128px]"></div>
        </div>
        <PageBackground3D theme="terms" />

        <div className="max-w-7xl mx-auto px-6 relative z-10">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-md border border-line-strong bg-paper eyebrow mb-8">
              <span className="w-1.5 h-1.5 rounded-full bg-brand"></span>
              Legal
            </div>
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight leading-tight">
              <span className="text-ink">
                Terms &amp;
              </span>
              <br />
              <span className="bg-brand bg-clip-text text-transparent">
                Conditions
              </span>
            </h1>
            <p className="mt-6 text-lg text-ink-muted max-w-3xl mx-auto leading-relaxed">
              Please read these terms of use carefully before using our platform.
            </p>
          </div>

          <div className="mt-20 max-w-4xl mx-auto">
            <div className="rounded-lg panel border border-line p-8 md:p-12 space-y-10 bg-paper/40">
              
              <div className="space-y-4">
                <p className="text-sm text-ink-muted leading-relaxed">
                  This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                <p className="text-sm text-ink-muted leading-relaxed">
                  This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <a href="https://blue-by-imergene.vercel.app" className="text-brand hover:underline">https://blue-by-imergene.vercel.app</a> (&quot;Website&quot;), including the related mobile site and mobile application (hereinafter referred to as &quot;Platform&quot;).
                </p>
                <p className="text-sm text-ink-muted leading-relaxed">
                  The Platform is owned and operated by IMERGENE (doing business as &quot;Blue By Imergene&quot;), a company incorporated under the Companies Act, 1956 or Companies Act, 2013 (as applicable), with its registered office at Samruddhi Nagar, Punyashri Nagri, Kupwad Road, Miraj, Sangli, Maharashtra – 416416 (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
                </p>
                <p className="text-sm text-ink-muted leading-relaxed">
                  Your use of the Platform, services, and tools is governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform, including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these terms and conditions including the policies constitute your binding obligations with the Platform Owner. These Terms of Use relate to your use of our Website, goods (as applicable), or services (as applicable) (collectively, &quot;Services&quot;). Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                </p>
                <p className="text-sm text-ink-muted leading-relaxed">
                  For the purpose of these Terms of Use, wherever the context so requires &quot;you&quot;, &quot;your&quot;, or &quot;user&quot; shall mean any natural or legal person who has agreed to become a user of the Platform.
                </p>
                <p className="text-sm font-semibold text-ink leading-relaxed bg-brand/10 border border-brand/30 p-4 rounded-lg">
                  ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                </p>
              </div>

              <div className="pt-8 border-t border-line space-y-6">
                <h2 className="text-xl font-bold text-ink">Terms of Platform and Services Use</h2>
                
                <ol className="list-decimal pl-5 space-y-6 text-sm text-ink-muted">
                  <li className="leading-relaxed pl-2">
                    To access and use the Services, you agree to provide true, accurate, and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.
                  </li>
                  <li className="leading-relaxed pl-2">
                    Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials offered on this Website or through the Services for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors, and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.
                  </li>
                  <li className="leading-relaxed pl-2">
                    Your use of our Services and the Platform is solely and entirely at your own risk and discretion, for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.
                  </li>
                  <li className="leading-relaxed pl-2">
                    The content of the Platform and the Services is proprietary to us and/or licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The content includes, but is not limited to, the design, layout, look, and graphics.
                  </li>
                  <li className="leading-relaxed pl-2">
                    You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.
                  </li>
                  <li className="leading-relaxed pl-2">
                    You agree to pay us the charges associated with availing the Services.
                  </li>
                  <li className="leading-relaxed pl-2">
                    You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal, or forbidden by these Terms, or Indian or local laws that might apply to you.
                  </li>
                  <li className="leading-relaxed pl-2">
                    You agree and acknowledge that the Website and the Services may contain links to other third-party websites. On accessing these links, you will be governed by the terms of use, privacy policy, and such other policies of such third-party websites. These links are provided for your convenience to provide further information.
                  </li>
                  <li className="leading-relaxed pl-2">
                    You understand that upon initiating a transaction for availing the Services, you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
                  </li>
                  <li className="leading-relaxed pl-2">
                    You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies (as applicable), and their respective officers, directors, agents, and employees, from any claim, demand, or actions (including reasonable attorney&apos;s fees) made by any third party or penalty imposed due to or arising out of your breach of these Terms of Use, Privacy Policy, and other policies, or your violation of any law, rules, or regulations, or the rights (including infringement of intellectual property rights) of a third party.
                  </li>
                  <li className="leading-relaxed pl-2">
                    Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                  </li>
                  <li className="leading-relaxed pl-2">
                    These Terms and any dispute or claim relating to them, or their enforceability, shall be governed by and construed in accordance with the laws of India.
                  </li>
                  <li className="leading-relaxed pl-2">
                    All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Sangli, Maharashtra, India.
                  </li>
                  <li className="leading-relaxed pl-2">
                    All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this Website.
                  </li>
                </ol>
              </div>

            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
