-- Canonical coupon store shared by blue-admin and blue-portal.
-- Dates use epoch milliseconds to support legacy admin coupon imports.
begin;
create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text unique not null check (code = upper(trim(code)) and code ~ '^[A-Z0-9][A-Z0-9_-]{0,63}$'),
  description text,
  reward_amount numeric(18, 10) not null check (reward_amount > 0),
  reward_type text not null default 'imr' check (reward_type = 'imr'),
  max_uses integer not null default 0 check (max_uses >= 0),
  per_user_limit integer not null default 1 check (per_user_limit > 0),
  times_used integer not null default 0 check (times_used >= 0),
  valid_from bigint,
  expires_at bigint,
  is_active boolean not null default true,
  created_at bigint not null default (extract(epoch from clock_timestamp()) * 1000)::bigint,
  check (expires_at is null or valid_from is null or expires_at > valid_from)
);
create table if not exists public.coupon_redemptions (
  id bigint generated by default as identity primary key,
  coupon_code text not null,
  user_id text not null,
  user_email text,
  reward_amount numeric(18, 10),
  redeemed_at bigint not null default (extract(epoch from clock_timestamp()) * 1000)::bigint
);
create index if not exists coupon_redemptions_user_code_idx on public.coupon_redemptions(coupon_code, user_id);
alter table public.coupons enable row level security;
alter table public.coupon_redemptions enable row level security;
revoke all on public.coupons, public.coupon_redemptions from anon, authenticated;
grant all on public.coupons, public.coupon_redemptions to service_role;
grant usage, select on sequence public.coupons_id_seq, public.coupon_redemptions_id_seq to service_role;

create or replace function public.claim_imr_coupon(user_id_param uuid, coupon_code_param text)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  selected public.coupons%rowtype;
  claims integer;
  balance_after numeric;
  now_ms bigint := (extract(epoch from clock_timestamp()) * 1000)::bigint;
  verified_email text;
begin
  if user_id_param is null or coupon_code_param is null
    or upper(trim(coupon_code_param)) !~ '^[A-Z0-9][A-Z0-9_-]{0,63}$' then
    return jsonb_build_object('success', false, 'status', 400, 'error', 'Please enter a valid coupon code.');
  end if;
  -- Serialize all claims for this coupon, including global and per-user limits.
  select * into selected from public.coupons where code = upper(trim(coupon_code_param)) for update;
  if not found then return jsonb_build_object('success', false, 'status', 404, 'error', 'Invalid coupon code.'); end if;
  if not selected.is_active then return jsonb_build_object('success', false, 'status', 400, 'error', 'This coupon is no longer active.'); end if;
  if selected.reward_type <> 'imr' then return jsonb_build_object('success', false, 'status', 400, 'error', 'This coupon does not award IMR.'); end if;
  if selected.valid_from is not null and now_ms < selected.valid_from then
    return jsonb_build_object('success', false, 'status', 400, 'error', 'This coupon is not active yet.');
  end if;
  if selected.expires_at is not null and now_ms >= selected.expires_at then
    return jsonb_build_object('success', false, 'status', 400, 'error', 'This coupon has expired.');
  end if;
  if selected.max_uses > 0 and selected.times_used >= selected.max_uses then
    return jsonb_build_object('success', false, 'status', 400, 'error', 'This coupon has reached its usage limit.');
  end if;
  select email into verified_email from auth.users where id = user_id_param;
  if not found then return jsonb_build_object('success', false, 'status', 401, 'error', 'Account not found.'); end if;
  select count(*) into claims from public.coupon_redemptions
    where coupon_code = selected.code and (user_id = user_id_param::text
      or (user_id like 'legacy:%' and lower(user_email) = lower(verified_email)));
  if claims >= selected.per_user_limit then
    return jsonb_build_object('success', false, 'status', 409, 'error', 'You have already claimed this coupon.');
  end if;
  -- Atomic addition preserves Blue credits/account_type and other wallet fields.
  insert into public.wallets(user_id, balance) values (user_id_param, selected.reward_amount)
    on conflict(user_id) do update set balance = public.wallets.balance + excluded.balance
    returning balance into balance_after;
  insert into public.coupon_redemptions(coupon_code, user_id, user_email, reward_amount, redeemed_at)
    values (selected.code, user_id_param::text, verified_email, selected.reward_amount, now_ms);
  update public.coupons set times_used = times_used + 1 where id = selected.id;
  return jsonb_build_object('success', true, 'rewardAmount', selected.reward_amount, 'newBalance', balance_after,
    'message', 'Coupon claimed successfully.');
end;
$$;
revoke all on function public.claim_imr_coupon(uuid, text) from public, anon, authenticated;
grant execute on function public.claim_imr_coupon(uuid, text) to service_role;

-- One-time, idempotent import of admin's former Neon/SQLite coupon store.
-- Never re-credit wallets, overwrite live coupons, or reset usage history.
create or replace function public.import_legacy_imr_coupons(payload jsonb)
returns jsonb language plpgsql security definer set search_path = public, pg_temp as $$
declare
  coupon jsonb;
  redemption jsonb;
  normalized_code text;
  imported_id bigint;
  ledger_count integer;
  unidentifiable_count integer;
  declared_count integer;
  imported_count integer := 0;
  disabled_count integer := 0;
  skipped_count integer := 0;
begin
  if jsonb_typeof(payload->'coupons') is distinct from 'array'
    or jsonb_typeof(payload->'redemptions') is distinct from 'array'
    or jsonb_array_length(payload->'coupons') > 5000
    or jsonb_array_length(payload->'redemptions') > 50000 then
    raise exception 'Invalid or oversized legacy import';
  end if;
  perform pg_advisory_xact_lock(hashtext('blue:legacy-coupon-import'));
  for coupon in select value from jsonb_array_elements(payload->'coupons') loop
    normalized_code := upper(trim(coupon->>'code'));
    if normalized_code is null or normalized_code !~ '^[A-Z0-9][A-Z0-9_-]{0,63}$'
      or lower(coalesce(coupon->>'reward_type', '')) <> 'imr' then
      skipped_count := skipped_count + 1;
      continue;
    end if;
    declared_count := greatest(0, coalesce((coupon->>'times_used')::integer, 0));
    imported_id := null;
    insert into public.coupons(code, description, reward_amount, reward_type, max_uses,
      per_user_limit, times_used, valid_from, expires_at, is_active, created_at)
      values (normalized_code, coupon->>'description', (coupon->>'reward_amount')::numeric, 'imr',
        coalesce((coupon->>'max_uses')::integer, 0), coalesce((coupon->>'per_user_limit')::integer, 1),
        declared_count, (coupon->>'valid_from')::bigint, (coupon->>'expires_at')::bigint,
        lower(coalesce(coupon->>'is_active', 'false')) in ('1', 'true'),
        coalesce((coupon->>'created_at')::bigint, (extract(epoch from clock_timestamp()) * 1000)::bigint))
      on conflict(code) do nothing returning id into imported_id;
    if imported_id is null then skipped_count := skipped_count + 1; continue; end if;
    ledger_count := 0;
    unidentifiable_count := 0;
    for redemption in select value from jsonb_array_elements(payload->'redemptions')
      where upper(trim(value->>'coupon_code')) = normalized_code loop
      if nullif(trim(redemption->>'user_id'), '') is null
        and nullif(trim(redemption->>'user_email'), '') is null then
        unidentifiable_count := unidentifiable_count + 1;
      end if;
      insert into public.coupon_redemptions(coupon_code, user_id, user_email, reward_amount, redeemed_at)
        values (normalized_code,
          case when redemption->>'user_id' ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
            then lower(redemption->>'user_id') else 'legacy:' || coalesce(redemption->>'user_id', '') end,
          redemption->>'user_email', (redemption->>'reward_amount')::numeric,
          coalesce((redemption->>'redeemed_at')::bigint, (extract(epoch from clock_timestamp()) * 1000)::bigint));
      ledger_count := ledger_count + 1;
    end loop;
    if declared_count > ledger_count or unidentifiable_count > 0 then
      update public.coupons set is_active = false where id = imported_id;
      disabled_count := disabled_count + 1;
    end if;
    update public.coupons set times_used = greatest(declared_count, ledger_count) where id = imported_id;
    imported_count := imported_count + 1;
  end loop;
  return jsonb_build_object('imported', imported_count, 'disabled', disabled_count, 'skipped', skipped_count);
end;
$$;
revoke all on function public.import_legacy_imr_coupons(jsonb) from public, anon, authenticated;
grant execute on function public.import_legacy_imr_coupons(jsonb) to service_role;
commit;
